import Head from 'next/head'
import Navbar from './components/Navbar'
import Productmenu from './components/ProductMenu'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Productmenu />
      
    </div>
  )
}
